### ISSUE TITLE
Migrate GitHub discussions from old socialconnect repo to new social-connect repo

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/social-connect#166]
There are many valuable technical discussions in the GitHub discussion section of the archived SocialConnect repo: 
- https://github.com/celo-org/SocialConnect/discussions

![Image](https://github.com/celo-org/social-connect/assets/46296830/fecd1b1e-32f8-49cd-9bc5-161d45a023eb)

Discussions can be moved between repositories (as far as I know). These discussions should be moved to the GitHub discussion section of the new SocialConnect repo:
- https://github.com/celo-org/social-connect/discussions/

**Comment by 0xarthurxyz** [comment]
Migrating the discussions would prevent possibly duplicate questions like these:

- https://github.com/celo-org/social-connect/issues/145
- https://github.com/celo-org/SocialConnect/discussions/3

**Comment by therealharpaljadeja** [comment]
Looks like we need unarchive the old repo first @0xarthurxyz 



![Image](https://github.com/celo-org/social-connect/assets/38040789/ad469122-cb5f-4289-931d-5752061fcf59)

**Comment by 0xarthurxyz** [comment]
Feel free to ask the IT team to un-archive the repo and ask them to re-archive when you are done.

**Comment by therealharpaljadeja** [comment]
@arthurgousset can we close this?
